services:
  homeconomy-api:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: ./api
    container_name: homeconomy-api
    hostname: homeconomy-api
    networks:
      - homeconomy-net
    ports:
      - 8282:8086
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "homeconomy-api"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: postgres:18.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 3356:5432
    networks:
      - homeconomy-net
    volumes:
      - postgres-db:/var/lib/postgres
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - homeconomy-net

  ui:
    depends_on:
      homeconomy-api:
        condition: service_healthy
    build:
      context: ./ui
    ports:
      - 8080:8080
    networks:
      - homeconomy-net

networks:
  homeconomy-net:
    driver: bridge

volumes:
  postgres-db: